export const environment = {
  production: true,
  LOGIN_URL: 'https://msg.messapp.site/public/api/login',
  REGISTER_URL: 'https://msg.messapp.site/public/api/register',
  UPDATE_USER: 'https://msg.messapp.site/public/api/update/',
  SHOW_USER: 'https://msg.messapp.site/public/api/show/',
  USER_NAME: 'https://msg.messapp.site/public/api/showname/',
  ALL_USERS: 'https://msg.messapp.site/public/api/showall/',
  CHANGE_IMG: 'https://msg.messapp.site/public/api/image/',
  CLOUD_IMG: 'https://api.cloudinary.com/v1_1/dfwiywprm/image/upload/',
  CREATE_MSG: 'https://msg.messapp.site/public/api/text/',
  GET_ID: 'https://msg.messapp.site/public/api/getid/',
  GET_MSG: 'https://msg.messapp.site/public/api/gettext/',
  BLOCK_USER: 'https://msg.messapp.site/public/api/block/',
  UNBLOCK_USER: 'https://msg.messapp.site/public/api/unblock/',
  GET_BLOCKED: 'https://msg.messapp.site/public/api/getblocked/',
  GET_NAME: 'https://msg.messapp.site/public/api/getname/',
  URL_IMG: `https://res.cloudinary.com/dfwiywprm/image/upload/v1673365846/message_api/`,
  DEFAULT_IMG: 'assets/img/profile3.png',
  GET_USER_BY_NAME: 'https://msg.messapp.site/public/api/userbyname/',
  NEW_MSG_NAME: 'https://msg.messapp.site/public/api/getnotread/',
  SET_READED: 'https://msg.messapp.site/public/api/setreaded/'
};
